version: '3.8'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=product-management
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_CHARACTER_SET_SERVER=utf8
      - MYSQL_COLLATION_SERVER=utf8_general_ci
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "1234" ]