### 사장님 로그인 - 성공
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "phoneNumber": "01012345678",
  "password": "password"
}

### 사장님 로그인 - 실패 (UNAUTHORIZED)
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "phoneNumber": "",
  "password": ""
}

### 사장님 로그아웃 - 성공
POST http://localhost:8080/v1/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc1NDcxODksImV4cCI6MTcwNzYzMzU4OX0.w0YdW50EZIcZovpyyag66WWU6Cxxn1AzI1QGH9MdB_c
# fill in token to Authorization header

{
}

### 사장님 로그아웃 - 실패 (UNAUTHORIZED)
POST http://localhost:8080/v1/logout
Content-Type: application/json

{
}
