### 상품 등록 - 성공
POST http://localhost:8080/v1/stores/1/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
  "price": 10000,
  "cost": 5000,
  "name": "name1 name2",
  "description": "description",
  "barcode": "1234567890",
  "expirationDate": "2024-12-31T00:00:00",
  "size": "SMALL",
  "categoryIds": [
    1
  ]
}

### 상품 등록 - 실패
POST http://localhost:8080/v1/stores/1/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
  "price": 10000,
  "cost": 5000,
  "name": "",
  "description": "",
  "barcode": "",
  "expirationDate": "2024-12-31T00:00:00",
  "size": "",
  "categoryIds": [
    1
  ]
}

### 상품 업데이트 - 성공
POST http://localhost:8080/v1/stores/1/products/1/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
  "price": 20000,
  "cost": 10000,
  "name": "name3 name4",
  "description": "description",
  "barcode": "1234567890",
  "expirationDate": "2024-12-31T00:00:00",
  "size": "LARGE",
  "categoryIds": [
    2
  ]
}


### 상품 업데이트 - 실패 (BAD_REQUEST)
POST http://localhost:8080/v1/stores/1/products/1/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
  "price": 10000,
  "cost": 5000,
  "name": "name1 name2",
  "description": "description",
  "barcode": "1234567890",
  "expirationDate": "2024-12-31T00:00:00",
  "size": "SMALL",
  "categoryIds": [
  ]
}

### 상품 삭제 - 성공
POST http://localhost:8080/v1/stores/1/products/1/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
}


### 상품 삭제 - 실패 (BAD_REQUEST)
POST http://localhost:8080/v1/stores/null/products/null/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM

{
}