### 가게 등록 - 성공
POST http://localhost:8080/v1/stores
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM
# fill in token to Authorization header

{
  "companyRegistrationNumber": "1234-567-890",
  "businessName": "businessName"
}

### 가게 등록 - 실패
POST http://localhost:8080/v1/stores
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiYXV0aGVudGljYXRpb24iLCJpYXQiOjE3MDc2MzY1MTEsImV4cCI6MTcwODUwMDUxMX0.0jCQf8OS8lntlO3U3cmFuwPfoBeRyjVc9J4BNXGCUSM
# fill in token to Authorization header

{
  "companyRegistrationNumber": "",
  "businessName": ""
}